shop/user/urls.py
from django.urls import path
from .views import RegistrationView, GoogleLoginView, GithubLoginView, Authorized_User_Page, LogoutView, LoginUserView

app_name = 'users'

urlpatterns = [
    path('registration/', RegistrationView.as_view(), name='registration_user'),
    path('google-login/', GoogleLoginView.as_view(), name='google_login'),
    path('github-login/', GithubLoginView.as_view(), name='github_login'),
    path('profile/', Authorized_User_Page.as_view(), name='profile_user'),
    path('logout/', LogoutView.as_view(), name='logout_view'),
    path('login/', LoginUserView.as_view(), name='login'),

]

shop/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class CustomUser(AbstractUser):
    cart = models.JSONField(default=dict, null=True, blank=True)  # Используйте JSONField для хранения корзины в виде словаря

shop/user/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.forms import PasswordInput
from user.models import CustomUser


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя', max_length=150)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Пароль', widget=PasswordInput)
    password2 = forms.CharField(label='Повторите Пароль', widget=PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username']
        if CustomUser.objects.filter(username=username).exists():
            raise forms.ValidationError('Пользователь с таким именем уже существует')
        return username

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', max_length=150)
    password = forms.CharField(label='Пароль', widget=PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('username', 'password')

shop/user/views.py
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from user.forms import UserRegistrationForm, UserLoginForm
from user.models import CustomUser


class LoginUserView(View):
    template_name = 'user/autification_user.html'
    form_class = UserLoginForm

    def get(self, request):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('product:index'))
        return render(request, self.template_name, {'form': form})


class RegistrationView(View):
    template_name = 'user/registration.html'
    form_class = UserRegistrationForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()  # Сохранение пользователя, но без записи в базу данных
            user.save()
            login(request, user)

            # Вместо перенаправления, отобразим сообщение на текущей странице
            message = 'Регистрация прошла успешно!'
            #return render(request, self.template_name, {'form': form, 'message': message})
            return HttpResponseRedirect(reverse('product:index'))
        else:
            print(form.errors)

        return render(request, self.template_name, {'form': form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('product:index')


class GoogleLoginView(View):
    def get_google(self, request):
        # Ваш код для аутентификации через Google
        # Возможно, вам понадобится использовать библиотеку python-social-auth
        return redirect('users:products_many')  # Замените 'home' на ваш URL после успешной аутентификации


class GithubLoginView(View):
    def get_git_hub(self, request):
        # Ваш код для аутентификации через GitHub
        # Возможно, вам понадобится использовать библиотеку python-social-auth
        return redirect('users:products_many')  # Замените 'home' на ваш URL после успешной аутентификации


class Authorized_User_Page(View):
    template_name = 'user/registration.html'

    def get(self, request):
        return render(request, self.template_name)

shop/user/templates/user/autification_user.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
    <link href="{% static 'vendor/css/registrations.css' %}" rel="stylesheet">
</head>
<body>

    <div class="container">
        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <h2>Авторизация</h2>
            <div class="input-group">
                <label for="{{ form.username.id_for_label }}">Имя пользователя:</label>
                {{ form.username }}
            </div>
            <div class="input-group">
                <label for="{{ form.password.id_for_label }}">Пароль:</label>
                {{ form.password }}
            </div>
            <button type="submit">Авторизоваться</button>
        </form>

        <div class="social-login">
            <p>Войти через:</p>
            <div class="social-account-container">
                <span class="title">Or Sign up with</span>
                <div class="social-accounts">
                    <button class="social-button google">
                        <svg class="svg" xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 488 512">
                            <path d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z"></path>
                        </svg>
                    </button>
                    <button class="social-button apple">
                        <svg class="svg" xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 384 512">
                            <path d="M318.7 268.7c-.2-36.7 16.4-64.4 50-84.8-18.8-26.9-47.2-41.7-84.7-44.6-35.5-2.8-74.3 20.7-88.5 20.7-15 0-49.4-19.7-76.4-19.7C63.3 141.2 4 184.8 4 273.5q0 39.3 14.4 81.2c12.8 36.7 59 126.7 107.2 125.2 25.2-.6 43-17.9 75.8-17.9 31.8 0 48.3 17.9 76.4 17.9 48.6-.7 90.4-82.5 102.6-119.3-65.2-30.7-61.7-90-61.7-91.9zm-56.6-164.2c27.3-32.4 24.8-61.9 24-72.5-24.1 1.4-52 16.4-67.9 34.9-17.5 19.8-27.8 44.3-25.6 71.9 26.1 2 49.9-11.4 69.5-34.3z"></path>
                        </svg>
                    </button>
                    <button class="social-button twitter">
                        <svg class="svg" xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512">
                            <path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"></path>
                        </svg>
                    </button>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

shop/user/templates/user/registration.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <link href="{% static 'vendor/css/registrations.css' %}" rel="stylesheet">
</head>
<body>

    <div class="container">
        <form action="{% url 'users:registration_user' %}" method="post">
            {% csrf_token %}
            <h2>Регистрация</h2>
            <div class="input-group">
                <label for="{{ form.username.id_for_label }}">Имя пользователя:</label>
                {{ form.username }}
            </div>
            <div class="input-group">
                <label for="{{ form.email.id_for_label }}">Email:</label>
                {{ form.email }}
            </div>
            <div class="input-group">
                <label for="{{ form.password1.id_for_label }}">Пароль:</label>
                {{ form.password1 }}
            </div>
            <div class="input-group">
                <label for="{{ form.password2.id_for_label }}">Повторите Пароль:</label>
                {{ form.password2 }}
            </div>
            <button type="submit">Зарегистрироваться</button>
        </form>

        <div class="social-login">
            <p>Войти через:</p>
            <div class="social-account-container">
                <span class="title">Or Sign up with</span>
                <div class="social-accounts">
                    <button class="social-button google">
                        <svg class="svg" xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 488 512">
                            <path d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z"></path>
                        </svg>
                    </button>
                    <button class="social-button apple">
                        <svg class="svg" xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 384 512">
                            <path d="M318.7 268.7c-.2-36.7 16.4-64.4 50-84.8-18.8-26.9-47.2-41.7-84.7-44.6-35.5-2.8-74.3 20.7-88.5 20.7-15 0-49.4-19.7-76.4-19.7C63.3 141.2 4 184.8 4 273.5q0 39.3 14.4 81.2c12.8 36.7 59 126.7 107.2 125.2 25.2-.6 43-17.9 75.8-17.9 31.8 0 48.3 17.9 76.4 17.9 48.6-.7 90.4-82.5 102.6-119.3-65.2-30.7-61.7-90-61.7-91.9zm-56.6-164.2c27.3-32.4 24.8-61.9 24-72.5-24.1 1.4-52 16.4-67.9 34.9-17.5 19.8-27.8 44.3-25.6 71.9 26.1 2 49.9-11.4 69.5-34.3z"></path>
                        </svg>
                    </button>
                    <button class="social-button twitter">
                        <svg class="svg" xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512">
                            <path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"></path>
                        </svg>
                    </button>
                </div>
            </div>
        </div>
    </div>

</body>
</html>