shop/product/urls.py
from django.urls import path
from .views import HelloWorldView, ProductCategoryShop, ProductShop

app_name = 'product'

urlpatterns = [
    path('', HelloWorldView.as_view(), name='index'),
    path('product/', ProductCategoryShop.as_view(), name='products_many'),
    path('product/<str:category_name>/', ProductShop.as_view(), name='products_shop'),
]

shop/product/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    img = models.ImageField('product_img')
    category = models.ForeignKey(to='ProductCategory', on_delete=models.CASCADE)

    def __str__(self):
        return f'Продукт {self.name}, Категория {self.category}'

shop/product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView
from product.models import ProductCategory, Product


# Create your views here.

class HelloWorldView(View):
    template_name = 'product/main.html'

    def get(self, request):
        return render(request, self.template_name)


class ProductCategoryShop(View):
    model = ProductCategory
    template_name = 'product/category_shop.html'

    def get(self, request):
        categories = ProductCategory.objects.all()
        print(categories)
        return render(request, self.template_name, {'categories': categories})


class ProductShop(View):
    template_name = 'product/product_shop.html'  # Название вашего шаблона

    def get(self, request, category_name):
        # Получаем категорию
        category = get_object_or_404(ProductCategory, name=category_name)

        # Получаем все товары в выбранной категории
        products = Product.objects.filter(category=category)

        # Передаем категорию и товары в контекст для отображения в шаблоне
        context = {'category': category, 'products': products}
        return render(request, self.template_name, context)

shop/product/templates/product/category_shop.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Список товаров</title>
    <link href="{% static 'vendor/css/category_product.css' %}" rel="stylesheet">
</head>
<body>

    <header>
        <h1>Мой магазин</h1>
    </header>

    <nav>
        <a href="/cabinet/">Кабинет</a>
        <a href="{% url 'cart:get_user_cart' %}">Корзина</a>
        <a href="/products/">Продукты</a>
    </nav>

    <main>
        <h2>Список Категорий товаров</h2>
        <div class="product-list">
            <!-- Здесь вставьте цикл для категорий -->
            {% for category in categories %}
            <div class="category">
                 <a href="{% url 'product:products_shop' category_name=category.name %}" class="category-button">
                    {{ category.name }}
            <!-- Добавьте другие поля категории, если нужно -->
                </a>
            </div>
            <!-- Повторите блок для каждой категории -->
            {% endfor %}
            <!-- Конец цикла для категорий -->
        </div>
    </main>

</body>
</html>

shop/product/templates/product/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Мой магазин</title>
    <link href="{% static 'vendor/css/main.css' %}" rel="stylesheet">
</head>
<body>

    <header>
        <h1>Мой магазин</h1>
    </header>

<!--    {% if user.is_authenticated %}-->
<!--        <nav>-->
<!--            <a href="/cabinet/">Кабинет</a>-->
<!--            <a href="/cccc/">Бонусы</a>-->
<!--            <a href="{% url 'product:products_many' %}">Продукты</a>-->
<!--            <a href="/cart/">Корзина</a>-->
<!--            <a href="/cart/">Выйти</a>-->
<!--        </nav>-->
<!--    {% else %}-->
<!--        <nav>-->
<!--            <a href="{% url 'users:registration_user' %}">Регистрация</a>-->
<!--            <a href="{% url 'product:products_many' %}">Продукты</a>-->
<!--            <a href="/cart/">Корзина</a>-->
<!--        </nav>-->
<!--    {% endif %}-->
<!--    <nav>-->
<!--        <a href="{% url 'users:registration_user' %}">Регистрация</a>-->
<!--        <a href="{% url 'product:products_many' %}">Продукты</a>-->
<!--        <a href="/cart/">Корзина</a>-->
    <nav>
        {% if user.is_authenticated %}
        <a href="/cabinet/">Кабинет</a>
        <a href="/cccc/">Бонусы</a>
        <a href="{% url 'cart:get_user_cart' %}">Корзина</a>
        <a href="{% url 'product:products_many' %}">Продукты</a>
        <a href="{% url 'users:logout_view' %}">Выйти</a>
        {% else %}
        <a href="{% url 'users:login' %}">Войти</a>
        <a href="{% url 'users:registration_user' %}">Регистрация</a>
        <a href="/fff/">О нас</a>
        {% endif %}
    </nav>

    <!-- Здесь можно добавить контент страницы -->

</body>
</html>

shop/product/templates/product/product_shop.html
<!-- Ваш файл category_view.html в директории templates/product/ -->
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ category.name }}</title>
    <link href="{% static 'vendor/css/category_product.css' %}" rel="stylesheet">
    <!-- Добавьте необходимые стили или ссылки на стили по вашему усмотрению -->
</head>
<body>

    <header>
        <h1>Мой магазин</h1>
    </header>

        <nav>
            <a href="/cabinet/">Кабинет</a>
            <a href="/cccc/">Бонусы</a>
            <a href="{% url 'cart:get_user_cart' %}">Корзина</a>
            <a href="{% url 'product:products_many' %}">Продукты</a>
        </nav>

    <main>
        <h2>Список товаров</h2>

        <div class="product-list">
            <!-- Здесь вставьте цикл для товаров -->
            {% for product in products %}
            <div class="product">
                <a href="#">
                    <img class="card-img-top"
                         src="{{ product.img.url }}"
                         alt="">
                </a>
                <h3>{{ product.name }}</h3>
                <p>Цена: {{ product.price }} рублей</p>
                <p>Описание: {{ product.description }}</p>
                <!--<button class="add-to-cart-button">Добавить в корзину</button>-->
                <a href="/cart/add_to_cart/{{product.id }}" class="btn btn-outline-success">Добавити в корзину</a>
                <!-- Добавьте другие поля товара, если нужно -->
            </div>
            <!-- Повторите блок для каждого товара -->
            {% endfor %}
            <!-- Конец цикла для товаров -->
        </div>
    </main>

</body>
</html>